// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function x(){function k(){var b=this.id;"menu2"==b?(g("menu-dnt"),x()):q!=b&&(v.querySelector("#"+q).className="nav",this.className="nav act",window.localStorage.bamenu=q=b,e(b))}function e(b){var a,d=v.querySelector("#box");"menu0"==b?a=[3,"blue","home.png",0,3,"blue","options.png",1,3,"blue","feedback.png",2,3,"blue","help.png",4,0,"blue","plugins.png",5,3,"blue","security.png",3,0,"blue","history.png",6,0,"blue","fcb32.png",8,0,"blue","youtube32.png",9,0,"blue","gpl32.png",10,0,"blue",
"rate32.png",11]:"menu1"==b&&(a=[3,"red","popular.png",0,3,"red","music.png",1,3,"red","trending.png",2,3,"red","sports.png",3,3,"red","news.png",4,3,"red","gaming.png",5,0,"red","beauty.png",10,0,"red","fashion.png",11,0,"red","food.png",12,0,"red","cooking.png",13]);var c=0;b=p.i18n.getMessage(b).split(";");for(var f=document.createDocumentFragment(),h,t,e,l,g,k,m,n,q,r,u=0;u<a.length;u+=4)m=u/4,e=a[u],k=a[u+1],n=a[u+2],2==e?(l=new Uint8Array(1),crypto.getRandomValues(l),l=l[0]%k.length,m="i"+(m+
l),k=k[l],n="i/menu/"+n[l],r=b[a[u+3]+l]):(m="i"+m,n="i/menu/"+n,r=b[a[u+3]]),7>e?(q=0,h=document.createElement("div"),t=document.createElement("div"),g=document.createElement("div"),l=new Image,k="btn "+k,2<e?(k+=" wide",h.className="btnBoxWide"):h.className="btnBox",t.id=m,t.className=k,l.className="icn",g.className="txt0",l.dataset.url=l.src=n,g.textContent=r,t.appendChild(l),t.appendChild(g),h.appendChild(t),f.appendChild(h)):(e=document.createElement("div"),h=document.createElement("div"),l=
new Image,l.src=n,e.id=m,e.className="adt a"+q,l.className="icnm",h.className="txt1",h.textContent=r,e.appendChild(l),t.insertBefore(e,g),t.insertBefore(h,g),q++),c++;d.innerHTML="";d.appendChild(f);d.style.display=""}function n(b){var a=parseInt((b.target.id?b.target:b.target.parentElement).id.slice(1)),d="https://appn.center/",c="menu-";"menu0"==q?0==a?w("https://www.mycinema.pro/",0,"https://plus.google.com/110367533603365326399/posts",0,"-home"):1==a?p.runtime.sendMessage(JSON.stringify({id:7})):
2==a?w("https://www.mycinema.pro/support.html",0,"https://plus.google.com/110367533603365326399/posts",0,"-support"):3==a?w("https://www.mycinema.pro/help-and-tips-for-chromium.html",0,"https://plus.google.com/110367533603365326399/posts",0,"-help"):4==a?(g(c+"plugins"),m("chrome://components")):5==a?w("https://www.hotcleaner.com/clickclean-app.html",1,"https://myaccount.google.com/intro/privacycheckup/1",0,"-ccapp"):6==a?(g(c+"history"),m("https://www.youtube.com/my_history")):7==a?(g(c+"fb"),m("https://www.facebook.com/magicactions")):
8==a?(g(c+"yt"),m("https://www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1")):9==a?(g(c+"gplus"),m("https://plus.google.com/110367533603365326399/posts")):10==a&&(g(c+"rate"),m("https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews")):"menu1"==q&&(0==a?d+="most-popular-videos":1==a?(c+="popular",d+="most-popular-music-videos"):2==a?(c+="trending",d+="trending-videos"):3==a?(c+="sports",d+="most-popular-sports-videos"):4==a?
(c+="news",d+="latest-news-videos"):5==a?(c+="gaming",d+="most-popular-gaming-videos"):6==a?(c+="beauty",d+="most-popular-beauty-videos"):7==a?(c+="fashion",d+="most-popular-fashion-videos"):8==a?(c+="food",d+="most-popular-food-videos"):9==a&&(c+="cooking",d+="most-popular-cooking-videos"),g(c),m(d+".html?app=magicactions"));b.stopPropagation()}function w(b,a,d,c,f){r(function(h){h?(g("siteon-menu"+f),m(b,a)):(g("siteoff-menu"+f),m(d,c))})}function m(b,a){function d(a){p.windows.update(a.windowId,
{focused:!0})}p.tabs.query({url:b},function(c){if(c&&c.length)p.tabs.update(c[0].id,{active:!0},d);else if(a)try{p.windows.create({url:b,focused:!0,incognito:!0,state:"maximized"},function(){p.runtime.lastError&&p.tabs.create({url:b,active:!0},d)})}catch(f){p.tabs.create({url:b,active:!0},d)}else p.tabs.create({url:b,active:!0},d)})}function r(b){y("HEAD","https://www.mycinema.pro/",0,"text",function(a){!a||200!=a.code&&304!=a.code?b():b(1)})}function x(){for(var b="707474682f3a2f732e77777770617970636c2e61636d2f6f62692d67776e2f69636273656d3f6372643d5f64746e616f736f6e6973627526736e6569653d7773736d6162406572746569786d746f66736d636f2e65697426615f6e6d44653d6d746e616f206f6e69206f72666961674d632041636e696f746f266e736973685f6e706970263d31676e6f75633d7279745553".match(/.{1,2}/g),
a=[3,0,0,-3],d,c="",f=0,h=b.length;f<h;f++)d=a[f%4],c=f+d<h?c+String.fromCharCode(parseInt(b[f+d],16)):c+String.fromCharCode(parseInt(b[f],16));p.tabs.create({url:c,active:!0},function(){window.close()})}function g(b){p.runtime.sendMessage(JSON.stringify({id:20,ga:{ea:b}}))}function y(b,a,d,c,f){var h={code:0},e=new XMLHttpRequest;e.open(b,a,!0);c&&(e.responseType=c);e.onload=function(a){h.code=this.status||0;h.data=this.response;f(h)};e.onerror=function(){f(h)};e.onabort=function(){f(h)};e.send(d)}
var q=window.localStorage&&window.localStorage.bamenu||"menu0";(function(){var b=v,a=document.createElement("link");a.rel="stylesheet";a.type="text/css";a.href="css/Xb.css";b.appendChild(a);var b=p.i18n.getMessage("menu").split(";"),a=document.createDocumentFragment(),d=document.createElement("div"),c=document.createElement("div"),f,h;d.id="menu";c.id="box";a.appendChild(d);a.appendChild(c);for(var g=0;g<b.length;g++)h="menu"+g,f=document.createElement("div"),f.id=h,f.className="nav",f.textContent=
b[g],f.addEventListener("click",k,!1),d.appendChild(f),2==g&&(f.title="Securely via PayPal to webmaster@mixesoft.com");v.appendChild(a);e(q);c.addEventListener("click",n,!1);v.querySelector("#"+q).classList.add("act")})()}var r,v,p={},k=chrome.runtime.getURL("vfMs.html");0!=top.location.href.indexOf(k)&&(top.location.href=k);for(var n in chrome)if("object"==typeof chrome[n]&&(k=Object.getOwnPropertyDescriptor(chrome,n))){p[n]=k.value;k.value={};k.configurable=!1;k.writable=!1;try{Object.defineProperty(chrome,
n,k)}catch(z){p[n]=chrome[n]}}"attachShadow"in Element.prototype&&(r=Element.prototype.attachShadow,Element.prototype.attachShadow=void 0);window.addEventListener("DOMContentLoaded",function(){var k=document.body,e;if(e=r){b:{if(navigator.appVersion&&(e=navigator.appVersion.indexOf("Chrome/"),-1<e)){e=parseInt(navigator.appVersion.slice(e+7));break b}e=0}e=53<e}v=e?r.call(k,{mode:"closed"}):k;x()},!1);window.addEventListener("blur",function(){},!1)})();
