// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
chrome.runtime.onStartup.addListener(function(){});
(function(){function C(a){document.cookie&&-1<document.cookie.indexOf("s=1")?(p=D("st")||p,chrome.runtime.onMessage.addListener(w),chrome.browserAction.onClicked.addListener(x),b.a0&&b.a3&&chrome.contextMenus.onClicked.addListener(y),a&&h()):(document.cookie="s=1; expires=0; path=/",chrome.runtime.onMessage.addListener(w),chrome.browserAction.onClicked.addListener(x),b.a0&&b.a3?chrome.contextMenus.removeAll(function(){chrome.contextMenus.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]},
function(){chrome.contextMenus.onClicked.addListener(y)})}):chrome.contextMenus.removeAll(function(){}),1==b.nv?z(1):"7.2.0.5"!==b.ver?(a=p,h({nv:Math.floor(Math.random()*(a+10368E5-a+1))+a,ver:"7.2.0.5"}),setTimeout(r,2012)):2<b.nv&&b.nv<p?z():a&&h())}function x(){q(function(a){a?f("https://www.mycinema.pro/menu.html"):f(chrome.runtime.getURL("BhD.html"))})}function z(a){h({nv:0});a?q(function(a){a?(k({ea:"siteon-install"}),f("https://www.mycinema.pro/menu.html",0),f("https://www.hotcleaner.com/clickclean/install-magic.html",
0)):(k({ea:"siteoff-install"}),t())}):A(1);setTimeout(r,1912)}function A(a){b.sv=1;q(function(c){c?(k({ea:"siteon-update"}),f("https://www.mycinema.pro/menu.html",0),f("https://www.mycinema.pro/options.html",0)):a?setTimeout(A,2E3):(k({ea:"siteoff-update"}),t())})}function h(a){a&&("nv"in a&&(b.nv=a.nv),"ver"in a&&(b.ver=a.ver));var c=JSON.stringify(b);m="window.msg__='"+c+"'";try{chrome.storage.local.set({opt:c}),window.localStorage.setItem("opt",c)}catch(d){}a&&a.bub&&E(m)}function E(a){chrome.tabs.query({windowType:"normal",
url:"*://*.youtube.com/*",status:"complete"},function(c){for(var d=0,b=c.length;d<b;d++)chrome.tabs.executeScript(c[d].id,{code:a})})}function w(a,c,d){if(32==a)return-1<c.tab.index&&chrome.tabs.executeScript(c.tab.id,{code:m,runAt:"document_start"}),!1;if(0==a)return!1;if(a&&6==a.id)return F(a),!1;try{a=JSON.parse(a)}catch(l){return!1}if(0==a.id)return d({opt:b,url:c.tab.url,local:u}),u=!1,!0;if(2==a.id)f(a.url,a.incognito);else if(3==a.id){for(var e in a.opt)e in g&&"nv"!=e&&"ver"!=e&&(b[e]=a.opt[e]);
h({bub:!0})}else if(4==a.id){e=a.name;if("nv"==e||"ver"==e)return!1;e in g&&(b[e]=a.value,h({bub:!0}))}else{if(5==a.id)return d({value:b[a.name]}),!0;if(7==a.id)G();else if(8==a.id)H(a.url);else{if(9==a.id)return d(B),!0;if(11==a.id)chrome.windows.update(c.tab.windowId,{state:a.v?"fullscreen":"maximized"});else if(17==a.id)h({nv:0});else if(20==a.id)k(a.ga);else if(31==a.id)return chrome.tabs.query({url:a.url},function(c){a.tab=c.length?!0:!1;d(JSON.stringify(a))}),!0}}m="window.msg__='"+JSON.stringify(b)+
"'";return!1}function F(a){B=a;chrome.tabs.query({url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html"},function(c){c&&c.length&&chrome.tabs.update(c[0].id,{active:!0},function(){chrome.tabs.sendMessage(c[0].id,a)})})}function H(a){chrome.tabs.query({url:a},function(a){a&&a.length&&chrome.tabs.update(a[0].id,{active:!0},function(){})})}function G(){q(function(a){a?(k({ea:"siteon-bgopt"}),f("https://www.mycinema.pro/options.html",!1)):(k({ea:"siteoff-bgopt"}),t())})}function t(){u=
!0;f(chrome.runtime.getURL("KR.html"))}function f(a,c){function d(a){chrome.windows.update(a.windowId,{focused:!0})}chrome.tabs.query({url:a},function(b){if(b&&b.length)chrome.tabs.update(b[0].id,{active:!0},d);else if(c)try{chrome.windows.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){chrome.runtime.lastError&&chrome.tabs.create({url:a,active:!0},d)})}catch(l){chrome.tabs.create({url:a,active:!0},d)}else chrome.tabs.create({url:a,active:!0},d)})}function y(a,c){if(7840==
a.menuItemId){var d="https://www.youtube.com/results?search_query="+encodeURIComponent(a.selectionText);0==c.url.indexOf("https://www.youtube.com/")?chrome.tabs.update({url:d}):chrome.tabs.create({url:d,selected:!0})}}function r(){v("GET","https://clients2.google.com/service/update2/crx?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D7.2.0.5%26uc&_="+(new Date).getTime(),null,0,function(a){})}function q(a){v("HEAD","https://www.mycinema.pro/",0,"text",function(c){!c||200!=c.code&&304!=c.code?a():a(1)})}
function k(a){var c=a.ec?a.ec:"app",d=a.ea?a.ea:"unk";a=a.el?a.el:"mafy 7.2.0.5";b.uid||(b.uid=I());v("POST","https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+b.uid+"&t=event&ec="+c+"&ea="+d+"&el="+a,"text",function(){})}function v(a,c,d,b,l){var e={code:0},f=new XMLHttpRequest;f.open(a,c,!0);b&&(f.responseType=b);f.onload=function(a){e.code=this.status||0;e.data=this.response;l(e)};f.onerror=function(){l(e)};f.onabort=function(){l(e)};try{f.send(d)}catch(K){l(e)}}function I(){var a=
Math.random,c=(4294967296*a()>>>0).toString(16),b=((4294967296*a()&4294922239|16384)>>>0).toString(16),e=((4294967296*a()&3221225471|2147483648)>>>0).toString(16),a=(4294967296*a()>>>0).toString(16);8>c.length&&(c=("0000000"+c).slice(-8));8>b.length&&(b=("0000000"+b).slice(-8));8>e.length&&(e=("0000000"+e).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[c,b.slice(0,4),b.slice(4),e.slice(0,4),e.slice(4)+a].join("-")}function D(a){a=parseInt(window.localStorage[a]);return isNaN(a)?null:a}
var p=Date.now(),B,b,m,u,g={ver:"7.2.0.5",nv:1,sv:0,extURL:"",uid:"",mwvc:!0,color:"white",mwvcm:!0,mwvct:!1,mwvcr:!1,mwvci:1,gap:5,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,ha:!1,anns:!0,cin:!0,cina:!1,cini:1,cinf:!1,cinc:0,cint:0,pt:!1,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!0,a4:!0,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0},n=Object.getOwnPropertyDescriptor(chrome,"management");if(n){n.value={};n.configurable=!1;n.writable=
!1;try{Object.defineProperty(chrome,"management",n)}catch(a){}}try{chrome.runtime.setUninstallURL("https://www.mycinema.pro/support.html#chuhcaf")}catch(a){}setTimeout(r,1503);(function(a,b,d){chrome.storage.local.get(a,function(c){var e;try{e=JSON.parse(a in c?c[a]:window.localStorage[a])}catch(J){e=null}d(null===e||e.constructor!==b?null:e)})})("opt",Object,function(a){var c;b=a;if(null===b||void 0===b.ver)b=g,c=!0;else{for(var d in b)d in g?typeof b[d]!==typeof g[d]&&(b[d]=g[d],c=!0):(delete b[d],
c=!0);for(d in g)d in b||(b[d]=g[d],c=!0)}b.extURL=chrome.runtime.getURL("");m="window.msg__='"+JSON.stringify(b)+"'";C(c)})})();
