// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function x(){function h(){var b=this.id;"menu2"==b?(f("menu-dnt"),x()):q!=b&&(u.querySelector("#"+q).className="nav",this.className="nav act",window.localStorage.bamenu=q=b,d(b))}function d(b){var a,e=u.querySelector("#box");"menu0"==b?a=[3,"blue","home.png",0,3,"blue","options.png",1,3,"blue","feedback.png",2,3,"blue","help.png",4,0,"blue","plugins.png",5,3,"blue","security.png",3,0,"blue","history.png",6,0,"blue","fcb32.png",8,0,"blue","youtube32.png",9,0,"blue","gpl32.png",10,0,"blue",
"rate32.png",11]:"menu1"==b&&(a=[3,"red","popular.png",0,3,"red","music.png",1,3,"red","trending.png",2,3,"red","sports.png",3,3,"red","news.png",4,3,"red","gaming.png",5,0,"red","beauty.png",10,0,"red","fashion.png",11,0,"red","food.png",12,0,"red","cooking.png",13]);var c=0;b=p.i18n.getMessage(b).split(";");for(var v=document.createDocumentFragment(),k,g,d,l,f,h,m,n,q,r,t=0;t<a.length;t+=4)m=t/4,d=a[t],h=a[t+1],n=a[t+2],2==d?(l=new Uint8Array(1),crypto.getRandomValues(l),l=l[0]%h.length,m="i"+(m+
l),h=h[l],n="i/menu/"+n[l],r=b[a[t+3]+l]):(m="i"+m,n="i/menu/"+n,r=b[a[t+3]]),7>d?(q=0,k=document.createElement("div"),g=document.createElement("div"),f=document.createElement("div"),l=new Image,h="btn "+h,2<d?(h+=" wide",k.className="btnBoxWide"):k.className="btnBox",g.id=m,g.className=h,l.className="icn",f.className="txt0",l.dataset.url=l.src=n,f.textContent=r,g.appendChild(l),g.appendChild(f),k.appendChild(g),v.appendChild(k)):(d=document.createElement("div"),k=document.createElement("div"),l=
new Image,l.src=n,d.id=m,d.className="adt a"+q,l.className="icnm",k.className="txt1",k.textContent=r,d.appendChild(l),g.insertBefore(d,f),g.insertBefore(k,f),q++),c++;e.innerHTML="";e.appendChild(v);e.style.display=""}function n(b){var a=parseInt((b.target.id?b.target:b.target.parentElement).id.slice(1)),e="https://appn.center/",c="menu-";"menu0"==q?0==a?r("https://www.mycinema.pro/",0,"https://plus.google.com/110367533603365326399/posts",0,"-home"):1==a?p.runtime.sendMessage(JSON.stringify({id:7})):
2==a?r("https://www.mycinema.pro/support.html",0,"https://plus.google.com/110367533603365326399/posts",0,"-support"):3==a?r("https://www.mycinema.pro/help-and-tips-for-chromium.html",0,"https://plus.google.com/110367533603365326399/posts",0,"-help"):4==a?(f(c+"plugins"),m("chrome://components")):5==a?r("https://www.hotcleaner.com/clickclean-app.html",1,"https://myaccount.google.com/intro/privacycheckup/1",0,"-ccapp"):6==a?(f(c+"history"),m("https://www.youtube.com/my_history")):7==a?(f(c+"fb"),m("https://www.facebook.com/magicactions")):
8==a?(f(c+"yt"),m("https://www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1")):9==a?(f(c+"gplus"),m("https://plus.google.com/110367533603365326399/posts")):10==a&&(f(c+"rate"),m("https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews")):"menu1"==q&&(0==a?e+="most-popular-videos":1==a?(c+="popular",e+="most-popular-music-videos"):2==a?(c+="trending",e+="trending-videos"):3==a?(c+="sports",e+="most-popular-sports-videos"):4==a?
(c+="news",e+="latest-news-videos"):5==a?(c+="gaming",e+="most-popular-gaming-videos"):6==a?(c+="beauty",e+="most-popular-beauty-videos"):7==a?(c+="fashion",e+="most-popular-fashion-videos"):8==a?(c+="food",e+="most-popular-food-videos"):9==a&&(c+="cooking",e+="most-popular-cooking-videos"),f(c),m(e+".html?app=magicactions"));b.stopPropagation()}function r(b,a,e,c,v){w(function(d){d?(f("siteon-menu"+v),m(b,a)):(f("siteoff-menu"+v),m(e,c))})}function m(b,a){function e(a){p.windows.update(a.windowId,
{focused:!0})}p.tabs.query({url:b},function(c){if(c&&c.length)p.tabs.update(c[0].id,{active:!0},e);else if(a)try{p.windows.create({url:b,focused:!0,incognito:!0,state:"maximized"},function(){p.runtime.lastError&&p.tabs.create({url:b,active:!0},e)})}catch(v){p.tabs.create({url:b,active:!0},e)}else p.tabs.create({url:b,active:!0},e)})}function w(b){y("HEAD","https://www.mycinema.pro/",0,"text",function(a){!a||200!=a.code&&304!=a.code?b():b(1)})}function x(){for(var b="707474682f3a2f732e77777770617970636c2e61636d2f6f62692d67776e2f69636273656d3f6372643d5f64746e616f736f6e6973627526736e6569653d7773736d6162406572746569786d746f66736d636f2e65697426615f6e6d44653d6d746e616f206f6e69206f72666961674d632041636e696f746f266e736973685f6e706970263d31676e6f75633d7279745553".match(/.{1,2}/g),
a=[3,0,0,-3],e,c="",d=0,k=b.length;d<k;d++)e=a[d%4],c=d+e<k?c+String.fromCharCode(parseInt(b[d+e],16)):c+String.fromCharCode(parseInt(b[d],16));p.tabs.create({url:c,active:!0},function(){window.close()})}function f(b){p.runtime.sendMessage(JSON.stringify({id:20,ea:b}))}function y(b,a,e,c,d){var k={code:0},g=new XMLHttpRequest;g.open(b,a,!0);c&&(g.responseType=c);g.onload=function(a){k.code=this.status||0;k.data=this.response;d(k)};g.onerror=function(){d(k)};g.onabort=function(){d(k)};g.send(e)}var q=
window.localStorage&&window.localStorage.bamenu||"menu0";(function(){var b=u,a=document.createElement("link");a.rel="stylesheet";a.type="text/css";a.href="css/SWS.css";b.appendChild(a);var b=p.i18n.getMessage("menu").split(";"),a=document.createDocumentFragment(),e=document.createElement("div"),c=document.createElement("div");e.id="menu";c.id="box";a.appendChild(e);a.appendChild(c);for(var f=0;f<b.length;f++){var k="menu"+f;var g=document.createElement("div");g.id=k;g.className="nav";g.textContent=
b[f];g.addEventListener("click",h,!1);e.appendChild(g);2==f&&(g.title="Securely via PayPal to webmaster@mixesoft.com")}u.appendChild(a);d(q);c.addEventListener("click",n,!1);u.querySelector("#"+q).classList.add("act")})()}var u,p={},h=chrome.runtime.getURL("aeP.html");0!=top.location.href.indexOf(h)&&(top.location.href=h);for(var n in chrome)if("object"==typeof chrome[n]&&(h=Object.getOwnPropertyDescriptor(chrome,n))){p[n]=h.value;h.value={};h.configurable=!1;h.writable=!1;try{Object.defineProperty(chrome,
n,h)}catch(z){p[n]=chrome[n]}}if("attachShadow"in Element.prototype){var w=Element.prototype.attachShadow;Element.prototype.attachShadow=void 0}window.addEventListener("DOMContentLoaded",function(){var h=document.body,d;if(d=w){b:{if(navigator.appVersion&&(d=navigator.appVersion.indexOf("Chrome/"),-1<d)){d=parseInt(navigator.appVersion.slice(d+7));break b}d=0}d=53<d}u=d?w.call(h,{mode:"closed"}):h;x()},!1);window.addEventListener("blur",function(){},!1)})();
