// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
chrome.runtime.onStartup.addListener(function(){});
(function(){function B(a){document.cookie&&-1<document.cookie.indexOf("s=1")?(p=C("st")||p,chrome.runtime.onMessage.addListener(v),chrome.browserAction.onClicked.addListener(w),b.a0&&b.a3&&chrome.contextMenus.onClicked.addListener(x),a&&h()):(document.cookie="s=1; expires=0; path=/",chrome.runtime.onMessage.addListener(v),chrome.browserAction.onClicked.addListener(w),b.a0&&b.a3?chrome.contextMenus.removeAll(function(){chrome.contextMenus.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]},
function(){chrome.contextMenus.onClicked.addListener(x)})}):chrome.contextMenus.removeAll(function(){}),1==b.nv?y(1):"7.2.0.8"!==b.ver?(a=p,h({nv:Math.floor(Math.random()*(a+10368E5-a+1))+a,ver:"7.2.0.8"}),setTimeout(r,2012)):2<b.nv&&b.nv<p?y():a&&h())}function w(){q(function(a){a?f("https://www.mycinema.pro/menu.html"):f(chrome.runtime.getURL("RNr.html"))})}function y(a){h({nv:0});a?q(function(a){a?(k("siteon-install"),f("https://www.mycinema.pro/menu.html",0),f("https://www.hotcleaner.com/clickclean/install-magic.html",
0)):(k("siteoff-install"),t())}):z(1);setTimeout(r,1912)}function z(a){b.sv=1;q(function(d){d?(k("siteon-update"),f("https://www.mycinema.pro/menu.html",0),f("https://www.mycinema.pro/options.html",0)):a?setTimeout(z,7E3):(k("siteoff-update"),t())})}function h(a){a&&("nv"in a&&(b.nv=a.nv),"ver"in a&&(b.ver=a.ver));var d=JSON.stringify(b);m="window.msg__='"+d+"'";try{chrome.storage.local.set({opt:d}),window.localStorage.setItem("opt",d)}catch(c){}a&&a.bub&&D(m)}function D(a){chrome.tabs.query({windowType:"normal",
url:"*://*.youtube.com/*",status:"complete"},function(d){for(var c=0,b=d.length;c<b;c++)chrome.tabs.executeScript(d[c].id,{code:a})})}function v(a,d,c){if(32==a)return-1<d.tab.index&&chrome.tabs.executeScript(d.tab.id,{code:m,runAt:"document_start"}),!1;if(0==a)return!1;if(a&&6==a.id)return E(a),!1;try{a=JSON.parse(a)}catch(l){return!1}if(0==a.id)return c({opt:b,url:d.tab.url}),!0;if(2==a.id)f(a.url,a.incognito);else if(3==a.id){for(e in a.opt)e in g&&"nv"!=e&&"ver"!=e&&(b[e]=a.opt[e]);h({bub:!0})}else if(4==
a.id){var e=a.name;if("nv"==e||"ver"==e)return!1;e in g&&(b[e]=a.value,h({bub:!0}))}else{if(5==a.id)return c({value:b[a.name]}),!0;if(7==a.id)F();else if(8==a.id)G(a.url);else{if(9==a.id)return c(A),!0;if(11==a.id)chrome.windows.update(d.tab.windowId,{state:a.v?"fullscreen":"maximized"});else if(17==a.id)h({nv:0});else if(20==a.id)k(a.ea);else if(31==a.id)return chrome.tabs.query({url:a.url},function(d){a.tab=d.length?!0:!1;c(JSON.stringify(a))}),!0}}m="window.msg__='"+JSON.stringify(b)+"'";return!1}
function E(a){A=a;chrome.tabs.query({url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html"},function(d){d&&d.length&&chrome.tabs.update(d[0].id,{active:!0},function(){chrome.tabs.sendMessage(d[0].id,a)})})}function G(a){chrome.tabs.query({url:a},function(a){a&&a.length&&chrome.tabs.update(a[0].id,{active:!0},function(){})})}function F(){q(function(a){a?(k("siteon-bgopt"),f("https://www.mycinema.pro/options.html",!1)):(k("siteoff-bgopt"),t())})}function t(){f(chrome.runtime.getURL("p.html"))}
function f(a,d){function c(a){chrome.windows.update(a.windowId,{focused:!0})}chrome.tabs.query({url:a},function(b){if(b&&b.length)chrome.tabs.update(b[0].id,{active:!0},c);else if(d)try{chrome.windows.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){chrome.runtime.lastError&&chrome.tabs.create({url:a,active:!0},c)})}catch(l){chrome.tabs.create({url:a,active:!0},c)}else chrome.tabs.create({url:a,active:!0},c)})}function x(a,d){if(7840==a.menuItemId){var b="https://www.youtube.com/results?search_query="+
encodeURIComponent(a.selectionText);0==d.url.indexOf("https://www.youtube.com/")?chrome.tabs.update({url:b}):chrome.tabs.create({url:b,selected:!0})}}function r(){u("GET","https://clients2.google.com/service/update2/crx?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D7.2.0.8%26uc&_="+(new Date).getTime(),null,0,function(a){})}function q(a){u("HEAD","https://www.mycinema.pro/",0,"text",function(d){!d||200!=d.code&&304!=d.code?a():a(1)})}function k(a){a=a||"unk";b.uid||(b.uid=H());u("POST","https://www.google-analytics.com/collect",
"v=1&tid=UA-326771-6&cid="+b.uid+"&t=event&ec=app&ea="+a+"&el=MA 7.2.0.8","text",function(){})}function u(a,d,b,e,l){var c={code:0},f=new XMLHttpRequest;f.open(a,d,!0);e&&(f.responseType=e);f.onload=function(a){c.code=this.status||0;c.data=this.response;l(c)};f.onerror=function(){l(c)};f.onabort=function(){l(c)};try{f.send(b)}catch(J){l(c)}}function H(){var a=Math.random,b=(4294967296*a()>>>0).toString(16),c=((4294967296*a()&4294922239|16384)>>>0).toString(16),e=((4294967296*a()&3221225471|2147483648)>>>
0).toString(16),a=(4294967296*a()>>>0).toString(16);8>b.length&&(b=("0000000"+b).slice(-8));8>c.length&&(c=("0000000"+c).slice(-8));8>e.length&&(e=("0000000"+e).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[b,c.slice(0,4),c.slice(4),e.slice(0,4),e.slice(4)+a].join("-")}function C(a){a=parseInt(window.localStorage[a]);return isNaN(a)?null:a}var p=Date.now(),A,b,m,g={ver:"7.2.0.8",nv:1,sv:0,extURL:"",uid:"",mwvc:!0,color:"white",mwvcm:!0,mwvct:!1,mwvcr:!1,mwvci:1,gap:5,hq:!0,hqi:"large",
pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,ha:!1,anns:!0,cin:!0,cina:!1,cini:1,cinf:!1,cinc:0,cint:0,pt:!1,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!0,a4:!0,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0},n=Object.getOwnPropertyDescriptor(chrome,"management");if(n){n.value={};n.configurable=!1;n.writable=!1;try{Object.defineProperty(chrome,"management",n)}catch(a){}}try{chrome.runtime.setUninstallURL("https://www.mycinema.pro/support.html#chuhcai")}catch(a){}setTimeout(r,
2712);(function(a,b,c){chrome.storage.local.get(a,function(d){try{var e=JSON.parse(a in d?d[a]:window.localStorage[a])}catch(I){e=null}c(null===e||e.constructor!==b?null:e)})})("opt",Object,function(a){b=a;if(null===b||void 0===b.ver){b=g;var d=!0}else{for(var c in b)c in g?typeof b[c]!==typeof g[c]&&(b[c]=g[c],d=!0):(delete b[c],d=!0);for(c in g)c in b||(b[c]=g[c],d=!0)}b.extURL=chrome.runtime.getURL("");m="window.msg__='"+JSON.stringify(b)+"'";B(d)})})();
