#!/bin/bash
if [ "$(playerctl status)" = "Playing" ]; then
  title=`exec playerctl metadata xesam:title`
  artist=`exec playerctl metadata xesam:artist`
  echo "$title - $artist"

elif [ "$(playerctl status)" = "Paused" ]; then
  title=`exec playerctl metadata xesam:title`
  artist=`exec playerctl metadata xesam:artist`
  echo "Paused: $title - $artist"

elif [ "$(playerctl status)" = "Connection to player failed: No players found" ]; then
  echo "Spotify disconnected"
fi
